name: Test checkout

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@int
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: slack api
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload: |
            {
              "text": "Test message from GitHub Actions - Dry Run"
            }
