name: Test Pass - Nested Annotated Tag Object SHA
on:
 workflow_dispatch:

permissions:
 contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Harden Runner
       uses: step-security/harden-runner@f1db3319d7db49c70352da1f5d1a122f754e8c01 # int
       with:
         disable-sudo: true
         egress-policy: audit
     - name: Checkout sources
       uses: actions/checkout@v6
     - name: Setup Java
       uses: actions/setup-java@v5
       with:
         distribution: 'temurin'
         java-version: 17
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4.4.3
