name: Test Pass - Nested Annotated Tag Object SHA
on:
 workflow_dispatch:

permissions:
 contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@48b5f213c81028ace310571dc5ec0fbbca0b2947
