name: Test checkout

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f1db3319d7db49c70352da1f5d1a122f754e8c01 # int
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        id: checkout-repo1
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: slack api
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        with:
          payload: |
            {
              "text": "Test message from GitHub Actions - Dry Run"
            }
